config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'prototypes#index'
  resources :prototypes do
    resources :likes, only: [:create, :destroy]
  end
  resources :popular, only: :index, module: :prototypes
  resources :comments, only: :create
  resources :tags, only: [:index, :show]
  resources :users, only: [:show, :edit, :update]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype, counter_cache: :comments_count

  validates :text, presence: true
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :prototype, counter_cache: :likes_count
  belongs_to :user
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :prototype_images, dependent: :delete_all
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :prototype_images
  validates :title, :catch_copy, :concept, presence: true
  paginates_per 8
  acts_as_taggable
  acts_as_ordered_taggable_on :prototypes

  def main_image
    prototype_images.main.first.image
  end

  def is_liked_by_current_user?(user_id)
    likes.find_by(user_id: user_id).present?
  end
end

app/models/prototype_image.rb
class PrototypeImage < ActiveRecord::Base
  belongs_to :prototype
  enum status: [:main, :sub]
  mount_uploader :image, PrototypeImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :nickname, presence: true
  mount_uploader :avatar, AvatarUploader
  has_many :prototypes
  has_many :likes
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :avatar, :member, :profile, :works])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :avatar, :member, :profile, :works])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: :create

  def create
    @prototype = Prototype.find(params[:comment][:prototype_id])
    @comment = current_user.comments.create(comment_params)
    @comments = @prototype.comments.includes(:user)
  end

  private
  def comment_params
    params.require(:comment).permit(:text, :prototype_id).merge(user_id: current_user.id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @prototype = Prototype.find(params[:prototype_id])
    @prototype.likes.create(user_id: current_user.id)
    @like = @prototype.likes.find_by(user_id: current_user)
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, prototype_id: params[:prototype_id]).destroy
    @prototype = Prototype.find(params[:prototype_id])
  end
end

app/controllers/prototypes/popular_controller.rb
class Prototypes::PopularController < ApplicationController
  def index
    @prototypes = Prototype.includes(:user).order(likes_count: :DESC).page(params[:page])
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :move_to_index, except: :index
  before_action :set_prototype, except: [:index, :new, :create]

  def index
    @prototypes = Prototype.order(created_at: :DESC).page(params[:page])
  end

  def show
    @like = @prototype.likes.find_by(user_id: current_user)
    @comment = Comment.new
    @comments = @prototype.comments.includes(:user)
  end

  def new
    @prototype = Prototype.new
    @prototype.prototype_images.build
  end

  def create
    @prototype = current_user.prototypes.new(prototype_params)
     @prototype.save ? ( redirect_to root_path, notice: 'Created successfully!' ) : ( redirect_to new_prototype_path, alert: 'Sorry, but something went wrong.' )
  end

  def edit
  end

  def update
    @prototype.update(prototype_params) ? ( redirect_to root_path, notice: 'Edited successfully!' ) : ( redirect_to edit_prototype_path, alert: 'Please fill in the blanks' )
  end

  def destroy
    @prototype.destroy
    redirect_to root_path, notice: 'Deleted successfully!'
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  private
  def prototype_params
    params.require(:prototype).permit(:title, :catch_copy, :concept, prototype_images_attributes: [:id, :status, :image]).merge(tag_list: params[:prototype][:tag])
  end

  def set_prototype
    @prototype = Prototype.find(params[:id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.most_used
  end

  def show
    @tag = ActsAsTaggableOn::Tag.find(params[:id])
    @prototypes = Prototype.tagged_with(@tag).includes(:user).page(params[:page])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :acquire_user_id
  before_action :authenticate_user!, except: :show

  def show
    @prototypes = @user.prototypes.order('created_at DESC')
  end

  def edit
  end

  def update
    current_user.update(update_params)
    if current_user.save
      redirect_to root_path, notice: 'Updated successfully'
    else
      render 'edit'
    end
  end

  private
  def update_params
    params.require(:user).permit(:nickname, :avatar, :profile, :member, :works)
  end

  def acquire_user_id
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.haml
.media
  .media-left
    = link_to user_path(comment.user_id) do
      = image_tag @prototype.user.avatar, class: 'media-object', size: '64x64'
  .media-body
    #top-aligned-media.media-heading
      = @prototype.user.nickname
    %p= comment.text

app/views/comments/create.js.erb
$('#comment_field').val('');
$('#comments-count').html("(<%= @comments.count %>)");
$('#js-comments').html("<%= j(render partial: 'comments/comment', collection: @comments) %>");

app/views/layouts/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    = button_tag data: { toggle: 'collapse', target: '.navbar-responsive-collapse' }, class: 'navbar-toggle' do
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = link_to '/', class: 'navbar-brand' do
      = image_tag 'logo.png', alt: 'PROTO TYPE - SHARE THE PROTOTYPE', height: '36px', class: 'navbar-brand'
    .navbar-collapse.collapse.navbar-responsive-collapse
      -if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            = link_to '#', aria: { expanded: false }, class: 'dropdown-toggle', data: { toggle: 'dropdown' }, role: 'button' do
              = current_user.nickname
              %span.caret
            %ul.dropdown-menu{ role: 'menu' }
              %li
                = link_to 'My Page', user_path(current_user)
              %li
                = link_to 'Profile Edit', edit_user_path(current_user)
              %li
                = link_to 'Logout', destroy_user_session_path, method: :delete
          %li
            .btn.btn-primary.navbar-btn
              = link_to 'New Proto', new_prototype_path
      -else
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              = link_to 'Get Started', new_user_session_path

app/views/layouts/_main_header.html.haml
.jumbotron
  .container.text-center
    = image_tag 'header_logo.png', alt: 'PROTO TYPE - SHARE THE PROTOTYPE', height: '73px'

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        - if current_page?(popular_index_path)
          %li.active{ role: 'presentation' }
            = link_to 'Popular PROTO', popular_index_path
          %li{ role: 'presentation' }
            = link_to 'Newest PROTO', root_path
        - else
          %li{role: 'presentation'}
            = link_to 'Popular PROTO', popular_index_path
          %li.active{role: 'presentation'}
            = link_to 'Newest PROTO', root_path
      = link_to 'View Tags', tags_path, { type: 'button', class: 'btn btn-default col-lg-1' }

app/views/layouts/_messages.html.haml
- flash.each do |key, value|
  - key = 'success' if key == 'notice'
  - key = 'danger'  if key == 'alert'
  %div{ class: "alert alert-#{key}" }
    = link_to 'x', '#', data: { dismiss: 'alert' }, class: 'close'
    %div
      = value

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', http:{ equiv: 'Content-Type' } }/
    %title Protospace
    = stylesheet_link_tag 'application', media: 'all', data: { turbolinks: { track: true } }
    = javascript_include_tag 'application', data: { turbolinks: { track: true } }
    = csrf_meta_tags
  %body
    = render 'layouts/messages'
    = render 'layouts/header'
    = yield
    = render 'layouts/footer'

app/views/likes/_like.html.haml
- if user_signed_in?
  - if like.present?
    = button_to prototype_like_path(like, prototype_id: prototype.id), method: :delete, class: 'btn btn-default', id: 'js-likes-button', data: {disable_with: 'sending now...'}, remote: true do
      = image_tag('/images/icon_red_heart.svg')
      LIKE
      %span.num= prototype.likes_count
  - else
    = button_to prototype_likes_path(prototype), method: :post, class: 'btn btn-default', id: 'js-likes-button', data: {disable_with: 'sending now...'}, remote: true do
      = image_tag('icon_heart.svg')
      LIKE
      %span.num= prototype.likes_count
- else
  = image_tag('icon_heart.svg')
  LIKE
  %span.num= prototype.likes_count

app/views/likes/create.js.erb
$("#js-like-buttons").html("<%= j(render partial: 'likes/like', locals: { prototype: @prototype, like: @like }) %>");

app/views/likes/destroy.js.erb
$("#js-like-buttons").html("<%= j(render partial: 'likes/like', locals: { prototype: @prototype, like: @like }) %>");

app/views/prototypes/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  .thumbnail
    = link_to prototype_path(prototype) do
      = image_tag prototype.main_image, size: '260x260'
    .caption
      %h3= prototype.title
      .proto-meta
        .proto-user
          = link_to prototype.user.nickname, user_path(prototype.user)
        .proto-posted
          Apr 26
      %ul.proto-tag-list.list-inline
        %li
        - prototype.tags.each do |tag|
          = link_to tag.name, tag_path(tag), class: 'btn btn-default'

app/views/prototypes/edit.html.haml
.container.proto-new
  = form_for @prototype do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          = f.text_field :title, placeholder: 'Title', class: 'proto-new-title'
      .row
        .col-md-12
          .cover-image-upload.js-preview-image
            = f.fields_for :prototype_images do |images_form|
              = images_form.file_field :image, class: 'cover-image-upload'
              = images_form.hidden_field :status, value: 'main'
        .col-md-12
          %ul.proto-sub-list.list-group
            %li.list-group-item.col-md-4
              .image-upload.js-preview-image
                = f.fields_for :prototype_images, (@prototype.prototype_images.sub.first) do |images_form|
                  = images_form.file_field :image, class: 'image-upload'
                  = images_form.hidden_field :status, value: 'sub'
            %li.list-group-item.col-md-4
              .image-upload.js-preview-image
                = f.fields_for :prototype_images, (@prototype.prototype_images.sub.second) do |images_form|
                  = images_form.file_field :image, class: 'image-upload'
                  = images_form.hidden_field :status, value: 'sub'
            %li.list-group-item.col-md-4
              .image-upload.js-preview-image
                = f.fields_for :prototype_images, (@prototype.prototype_images.sub.third) do |images_form|
                  = images_form.file_field :image, class: 'image-upload'
                  = images_form.hidden_field :status, value: 'sub'
        .row.proto-description
          .col-md-12
            = f.text_field :catch_copy, placeholder: 'Catch Copy'
          .col-md-12
            = f.text_field :concept, cols: '30', rows: '4', placeholder: 'Concept'
          .col-md-12
            %h4 Tag List
            .row
              - Settings.defaults.tag_placeholder.each do |tag|
                .col-md-3
                  = text_field_tag "prototype[tag_list][]", "", placeholder: "#{tag}"
        .row.text-center.proto-btn
          = f.submit "Publish", class: 'btn btn-lg btn-primary btn-block'

app/views/prototypes/index.html.haml
= render 'layouts/main_header'
.container.proto-list
  .row
    = render partial: "prototype", collection: @prototypes
.text-center
  %ul.pagination
    %li.disabled
      %span{ aria: { hidden: 'true' }}
        .pagination-design
          = paginate(@prototypes)

app/views/prototypes/new.html.haml
.container.proto-new
  = form_for @prototype do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          = f.text_field :title, placeholder: 'Title', class: 'proto-new-title'
      .row
        .col-md-12
          .cover-image-upload.js-preview-image
            = f.fields_for :prototype_images do |images_form|
              = images_form.file_field :image, class: 'cover-image-upload'
              = images_form.hidden_field :status, value: 'main'
        .col-md-12
          %ul.proto-sub-list.list-group
            - 3.times do
              %li.list-group-item.col-md-4
                .image-upload.js-preview-image
                  = f.fields_for :prototype_images do |images_form|
                    = images_form.file_field :image, class: 'image-upload'
                    = images_form.hidden_field :status, value: 'sub'
        .row.proto-description
          .col-md-12
            = f.text_field :catch_copy, placeholder: 'Catch Copy'
          .col-md-12
            = f.text_field :concept, cols: '30', rows: '4', placeholder: 'Concept'
          .col-md-12
            %h4 Tag List
            .row
              - Settings.defaults.tag_placeholder.each do |tag|
                .col-md-3
                  = text_field_tag "prototype[tag][]", "", placeholder: "#{tag}"
        .row.text-center.proto-btn
          = f.submit "Publish", class: 'btn btn-lg btn-primary btn-block'

app/views/prototypes/popular/index.html.haml
= render 'layouts/main_header'
.container.proto-list
  .row
    = render partial: "prototypes/prototype", collection: @prototypes
.text-center
  %ul.pagination
    %li.disabled
      %span{ aria: { hidden: 'true' }}
        = paginate(@prototypes)

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = link_to 'javascript:void(0)' do
            = image_tag @prototype.user.avatar, class: 'media-object', size: '64x64'
        .media-body
          %h4#top-aligned-media.media-heading
            = @prototype.title
            - if user_signed_in? && @prototype.user_id == current_user.id
              = link_to 'DELETE', prototype_path(@prototype), method: :delete, class: "btn btn-xs btn-primary navbar-btn"
              = link_to 'EDIT', edit_prototype_path(@prototype), class: "btn btn-xs btn-primary navbar-btn"
          .proto-user
            = link_to "#{@prototype.user.nickname}", user_path(@prototype.user)
            %span.degree we-b inc. Designer

    .col-md-6.text-right
      #js-like-buttons
        = render partial: "likes/like", locals: { prototype: @prototype, like: @like }
  .row
    .col-md-9
      = image_tag @prototype.main_image, class: 'img-responsive', size: '800x400'
    .col-md-3
      %ul.proto-sub-list.list-group
        - @prototype.prototype_images.sub.each do |sub_image|
          %li.list-group-item
            = image_tag sub_image.image, class: 'img-responsive'
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p= @prototype.catch_copy
    .col-md-6
      %h4 Concept
      %p= @prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        %li
        - @prototype.tags.each do |tag|
          = link_to tag.name, tag_path(tag), class: 'btn btn-default'
  .row.proto-comments
    %h4.col-md-12
      Comments
      %span.num#comments-count= "(#{@prototype.comments_count})"
    .col-md-8
      #js-comments
        = render partial: "comments/comment", collection: @comments
      .form-inline
        - if user_signed_in?
          = form_for @comment, remote: true do |f|
            %h4 Write a comment
            .row
              .form-group.col-md-10
                = f.text_area :text, placeholder: 'Your comments', rows: '3', class: 'textform-control', id: 'comment_field'
                = f.hidden_field :prototype_id, value: @prototype.id
              .form-group.col-md-2
                = f.submit 'Comment', class: 'button btn btn-primary'

app/views/tags/index.html.haml
.jumbotron
  .container.text-center
    = image_tag 'header_logo.png', alt: 'PROTO TYPE - SHARE THE PROTOTYPE', height: '73px'
.container
  .row
    %h2.tag-list
      Tag list
      %ul.proto-tag-list.list-inline
        %li
        - @tags.each do |tag|
          = link_to tag.name, tag_path(tag), class: 'btn btn-default'

app/views/tags/show.html.haml
= render 'layouts/main_header'
.container.proto-list
  .row
    = render @prototypes
.text-center
  %ul.pagination
    %li.disabled
      = paginate(@prototypes)

app/views/users/edit.html.haml
.container.user-new
  = form_for current_user do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h2 Edit Profile
          .user-name_image.row
            .user-name.col-md-10
              = f.text_field :nickname, placeholder: 'Username'
            .user-image.col-md-2.js-preview-image
              = f.button 'Change image', class: 'btn btn-primary'
              = f.file_field :avatar
          = f.email_field :email, placeholder: 'E-Mailail'
          = f.password_field :password, placeholder: 'Password', class: 'user-password'
        .col-md-12
          %h4 Member of
          .user-user-member.row
            .user-name.col-md-12
              = f.text_field :member, placeholder: 'Member'
          %h4 Profile
          .user-user-profile.row
            .user-name.col-md-12
              = f.text_area :profile, cols: '30', rows: '4', placeholder: 'Profile'
          %h4 Works
          .user-name_image.row
            .user-name.col-md-12
              = f.text_area :works, cols: '30', rows: '4', placeholder: 'Works'
      .row.text-center.user-btn
        = f.submit :save, class: 'btn btn-lg btn-primary btn-block'

app/views/users/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        = link_to '#' do
          = image_tag @user.avatar, class: 'media-object', size: '64x64'
      .media-body
        %h4#top-aligned-media.media-heading
          = @user.nickname
          %span.label.label-default.project-number
            = @user.prototypes.count
            %i Projects
        .proto-user
          %span.degree
            = @user.member
        .row
          .col-md-6
            %h4 Profile
            %p= @user.profile
          .col-md-6
            %h4 Works
            %p= @user.works
.container.proto-list
  .row
    = render partial: "prototypes/prototype", collection: @prototypes

.text-center
  %ul.pagination
    %li.disabled
      %a{ area: { label: 'Previous' }, href: '#' }
        %span{ aria: { hidden: 'true' }} «
    %li.active
      %a{ href: "#" }
        1
        %span.sr-only (current)
    %li
      %a{ href: "#" } 2
    %li
      %a{ href: "#" } 3
    %li
      %a{ href: "#" } 4
    %li
      %a{ href: "#" } 5
    %li
      %a{ area: { label: 'Next' }, href: '#' }
        %span{ aria: { hidden: 'true' }} »